import bcrypt from 'bcryptjs';

export const data = {
	users: [
		{
			name: 'Francis',
			email: 'admin@example.com',
			password: bcrypt.hashSync('123456', 11),
			isAdmin: true,
		},
		{
			name: 'Jane',
			email: 'user@example.com',
			password: bcrypt.hashSync('123456', 11),
			isAdmin: false,
		},
	],
	products: [
		{
			name: 'Symmetrical Hoodie',
			slug: 'symmetrical-hoodie',
			category: 'Shirts',
			image: '/images/shirt1.jpg',
			price: 200,
			brand: 'Subwae',
			rating: 4.3,
			numReviews: 8,
			countInStock: 20,
			description:
				'Symmetrical Hoodie. Pure narrative momentum through garment construction',
		},
		{
			name: 'Look 1 SS Shirt',
			slug: 'look1-ss-shirt',
			category: 'Shirts',
			image: '/images/shirt2.jpg',
			price: 600,
			brand: 'Subwae',
			rating: 3.5,
			numReviews: 10,
			countInStock: 20,
			description: 'Collection 22/23. SUBWAE STUDIOS Shirt. Variant 1',
		},
		{
			name: 'Soulful Simplicity T',
			slug: 'ss-simplicity-T',
			category: 'Shirts',
			image: '/images/shirt3.jpg',
			price: 300,
			brand: 'Subwae',
			rating: 4.0,
			numReviews: 3,
			countInStock: 20,
			description:
				'Soulful Simplicity Look 4. Subwae Studios/22-23. Heavy cotton and boxed fit',
		},
		{
			name: 'AS Skuba Pants',
			slug: 'skuba-pants',
			category: 'Pants',
			image: '/images/pant1.jpg',
			price: 450,
			brand: 'Subwae',
			rating: 4.0,
			numReviews: 13,
			countInStock: 20,
			description:
				'AS Skuba Pants. African Soil Collection. Very smooth and stretchy fabric. Vertical stripes accross the fabric',
		},
		{
			name: 'Complete Fit w/ Red Bag',
			slug: 'complete-fit-1',
			category: 'Pants',
			image: '/images/pant2.jpg',
			price: 899,
			brand: 'Subwae',
			rating: 4.0,
			numReviews: 13,
			countInStock: 20,
			description:
				'Subwae African Soil collection RED strap bag with Soulful Simplicity Shirt and Skirt  ',
		},
		{
			name: 'Complete Fit w/ White Bag',
			slug: 'complete-fit-2',
			category: 'Pants',
			image: '/images/pant3.jpg',
			price: 899,
			brand: 'Subwae',
			rating: 4.0,
			numReviews: 13,
			countInStock: 20,
			description:
				'Subwae African Soil collection GRAY strap bag with Soulful Simplicity Shirt and Skirt',
		},
		{
			name: 'Camper',
			slug: 'camper',
			category: 'Cap',
			image: '/images/cap1.jpg',
			price: 50,
			brand: 'Subwae',
			rating: 4.0,
			numReviews: 13,
			countInStock: 20,
			description: 'Nylon camper lightweight headwear',
		},
		{
			name: 'SS BAG',
			slug: 'ss-bag',
			category: 'Bag',
			image: '/images/bag1.jpg',
			price: 70,
			brand: 'Subwae',
			rating: 4.0,
			numReviews: 13,
			countInStock: 20,
			description: 'Soulful Simplicity 22/23 Collection. Strap Bag',
		},
		{
			name: '404 Error T',
			slug: '404-error-t',
			category: 'T-Shirts',
			image: '/images/errorT.jpg',
			price: 99,
			brand: 'Subwae',
			rating: 4.0,
			numReviews: 13,
			countInStock: 20,
			description:
				'Soulful Simplicity 22/23 Collection. For the Software Developer',
		},
	],
};
